#!/usr/bin/env bash
# ServerStick — Apply AI tier to Hermes
# Called by hermes-bridge when user picks tier in onboarding
#
# Usage: apply-tier.sh <tier>
# Reads: /etc/serverstick/tier.env (written by bridge)
#         /etc/serverstick/nemoclaw.env (written by bridge)
# Runs:  nemohermes onboard (non-interactive) → starts Hermes

set -euo pipefail

TIER_ENV="/etc/serverstick/tier.env"
NEMOCLAW_ENV="/etc/serverstick/nemoclaw.env"
SANDBOX="${NEMOCLAW_SANDBOX:-serverstick}"

log()  { echo -e "\033[0;34m[apply-tier]\033[0m $*"; }
ok()   { echo -e "\033[0;32m[apply-tier]\033[0m ✓ $*"; }
warn() { echo -e "\033[1;33m[apply-tier]\033[0m ⚠ $*"; }
err()  { echo -e "\033[0;31m[apply-tier]\033[0m ✗ $*" >&2; exit 1; }

TIER="${1:-}"
[[ -z "$TIER" ]] && err "Usage: apply-tier.sh <byo|local|managed>"

[[ ! -f "$TIER_ENV" ]] && { warn "$TIER_ENV missing, creating minimal"; mkdir -p "$(dirname "$TIER_ENV")"; echo "TIER=$TIER" > "$TIER_ENV"; }

# shellcheck disable=SC1090
source "$TIER_ENV"

log "Applying tier: $TIER"

# ─── Detect NemoClaw command ────────────────────────────────────────
if command -v nemohermes &>/dev/null; then
  NEMOCLAW_CMD="nemohermes"
elif command -v nemoclaw &>/dev/null; then
  NEMOCLAW_CMD="NEMOCLAW_AGENT=hermes nemoclaw"
else
  err "Neither nemohermes nor nemoclaw found — is NemoClaw installed?"
fi
log "Using: $NEMOCLAW_CMD"

# ─── Build nemoclaw.env from tier choices ───────────────────────────
log "Writing $NEMOCLAW_ENV..."

# Resolve variables from tier.env (already sourced)
case "$TIER" in
  byo)
    [[ -z "${OPENAI_API_KEY:-}" ]] && err "TIER=byo but OPENAI_API_KEY not set"
    [[ -z "${OPENAI_BASE_URL:-}" ]] && err "TIER=byo but OPENAI_BASE_URL not set"
    PROVIDER="openai"
    ;;
  local)
    PROVIDER="local"
    ;;
  managed)
    PROVIDER="openai"
    OPENAI_BASE_URL="${OPENAI_BASE_URL:-https://api.tokenrouter.com/v1}"
    ;;
  *)
    err "Unknown TIER: $TIER (must be byo, local, or managed)"
    ;;
esac

mkdir -p "$(dirname "$NEMOCLAW_ENV")"
cat > "$NEMOCLAW_ENV" << ENVEOF
# Generated by apply-tier.sh — do not edit manually
NEMOCLAW_AGENT=hermes
NEMOCLAW_NON_INTERACTIVE=1
NEMOCLAW_ACCEPT_THIRD_PARTY_SOFTWARE=1
NEMOCLAW_SANDBOX_NAME=${SANDBOX}
NEMOCLAW_HERMES_DASHBOARD_TUI=1
INFERENCE_PROVIDER=${PROVIDER}
INFERENCE_LOCAL_URL=${INFERENCE_LOCAL_URL:-http://localhost:8081}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
HERMES_MODEL=${HERMES_MODEL:-auto}
CHAT_UI_URL=${CHAT_UI_URL:-}
ENVEOF
chmod 600 "$NEMOCLAW_ENV"
ok "nemoclaw.env written"

# ─── Run NemoClaw onboard (non-interactive) ────────────────────────
log "Running NemoClaw onboard (non-interactive)..."

# Export all vars from nemoclaw.env so nemohermes can read them
set -a
# shellcheck disable=SC1090
source "$NEMOCLAW_ENV"
set +a

# Stop existing sandbox if running
$NEMOCLAW_CMD "$SANDBOX" stop 2>/dev/null || true

# Run onboard — this creates the sandbox, installs Hermes, sets up the agent
if $NEMOCLAW_CMD onboard 2>&1; then
  ok "NemoClaw onboard completed"
else
  warn "nemohermes onboard exited with error — attempting start anyway"
fi

# ─── Start Hermes ──────────────────────────────────────────────────
log "Starting Hermes sandbox $SANDBOX..."
$NEMOCLAW_CMD "$SANDBOX" start 2>&1 || warn "start command had issues"
sleep 5

# ─── Verify ────────────────────────────────────────────────────────
if curl -sf http://localhost:18789/api/health >/dev/null 2>&1; then
  ok "Hermes dashboard is up at http://localhost:18789"
else
  warn "Dashboard not responding yet — may still be starting"
fi

if curl -sf http://localhost:8642/v1/models >/dev/null 2>&1; then
  ok "Hermes OpenAI API is up at http://localhost:8642"
else
  warn "OpenAI API not responding yet on :8642"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Tier applied: $TIER"
echo "  Hermes dashboard: http://localhost:18789"
echo "  Hermes OpenAI API: http://localhost:8642"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
