#!/usr/bin/env bash
# ServerStick — Apply AI tier to Hermes
# Called by Svelte GUI when user picks tier in onboarding
#
# Usage: apply-tier.sh
# Reads: /etc/serverstick/tier.env (written by Svelte)
# Writes: /sandbox/.hermes/.env (inside NemoClaw), restarts Hermes

set -euo pipefail

TIER_ENV="/etc/serverstick/tier.env"
NEMOCLAW_ENV="/etc/serverstick/nemoclaw.env"
SANDBOX="${NEMOCLAW_SANDBOX:-serverstick}"
NEMOCLAW_CMD="nemohermes"

[[ ! -f "$TIER_ENV" ]] && { echo "Missing $TIER_ENV"; exit 1; }
[[ ! -f "$NEMOCLAW_ENV" ]] && { echo "Missing $NEMOCLAW_ENV"; exit 1; }

# shellcheck disable=SC1090
source "$TIER_ENV"
# shellcheck disable=SC1090
source "$NEMOCLAW_ENV"

log()  { echo -e "\033[0;34m[apply-tier]\033[0m $*"; }
ok()   { echo -e "\033[0;32m[apply-tier]\033[0m ✓ $*"; }
warn() { echo -e "\033[1;33m[apply-tier]\033[0m ⚠ $*"; }
err()  { echo -e "\033[0;31m[apply-tier]\033[0m ✗ $*" >&2; exit 1; }

log "Applying tier: $TIER"

# ─── Stop Hermes ────────────────────────────────────────────────────
log "Stopping Hermes sandbox $SANDBOX..."
$NEMOCLAW_CMD "$SANDBOX" stop 2>/dev/null || true

# ─── Tier-specific setup ────────────────────────────────────────────
case "$TIER" in
  local)
    log "Setting up local inference with llama.cpp..."
    MODEL_PATH="${HERMES_MODEL_PATH:-}"
    [[ -z "$MODEL_PATH" ]] && err "TIER=local but HERMES_MODEL_PATH not set"
    [[ ! -f "$MODEL_PATH" ]] && { log "Downloading model..."; mkdir -p "$(dirname "$MODEL_PATH")"; \
      curl -L "https://huggingface.co/.../$(basename "$MODEL_PATH")" -o "$MODEL_PATH"; }

    log "Starting llama.cpp server on port ${LLAMACPP_PORT:-8081}..."
    # Assume llama-server is installed; if not, install via apt or use bundled binary
    if ! command -v llama-server &>/dev/null; then
      warn "llama-server not found — install: apt install llama.cpp"
    fi
    nohup llama-server -m "$MODEL_PATH" \
      --port "${LLAMACPP_PORT:-8081}" \
      --ctx-size "${HERMES_CTX_SIZE:-4096}" \
      --threads "${HERMES_THREADS:-4}" \
      --n-gpu-layers "${HERMES_GPU_LAYERS:-0}" \
      > /var/log/llama-server.log 2>&1 &
    sleep 3
    ok "llama.cpp server started"

    export INFERENCE_PROVIDER=local
    export INFERENCE_LOCAL_URL="http://localhost:${LLAMACPP_PORT:-8081}"
    ;;

  byo)
    [[ -z "${OPENAI_API_KEY:-}" ]] && err "TIER=byo but OPENAI_API_KEY not set"
    [[ -z "${OPENAI_BASE_URL:-}" ]] && err "TIER=byo but OPENAI_BASE_URL not set"
    log "Using user-supplied key against $OPENAI_BASE_URL"
    export INFERENCE_PROVIDER=openai
    ;;

  managed)
    [[ -z "${OPENAI_API_KEY:-}" ]] && err "TIER=managed but OPENAI_API_KEY not set"
    log "Using TokenRouter account (XMR-funded)"
    export INFERENCE_PROVIDER=openai
    export OPENAI_BASE_URL="https://api.tokenrouter.com/v1"
    ;;

  *)
    err "Unknown TIER: $TIER (must be local, byo, or managed)"
    ;;
esac

# ─── Write env to sandbox ───────────────────────────────────────────
log "Writing Hermes env to sandbox..."
SANDBOX_ENV="# Generated by apply-tier.sh — do not edit manually
NEMOCLAW_AGENT=hermes
NEMOCLAW_NON_INTERACTIVE=1
NEMOCLAW_SANDBOX_NAME=$SANDBOX
NEMOCLAW_HERMES_DASHBOARD_TUI=${NEMOCLAW_HERMES_DASHBOARD_TUI:-1}
INFERENCE_PROVIDER=${INFERENCE_PROVIDER:-local}
INFERENCE_LOCAL_URL=${INFERENCE_LOCAL_URL:-http://localhost:8081}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
HERMES_MODEL=${HERMES_MODEL:-}
CHAT_UI_URL=${CHAT_UI_URL:-}
"
echo "$SANDBOX_ENV" | $NEMOCLAW_CMD "$SANDBOX" exec tee /sandbox/.hermes/.env >/dev/null
ok "Sandbox env written"

# ─── Start Hermes ───────────────────────────────────────────────────
log "Starting Hermes sandbox $SANDBOX..."
$NEMOCLAW_CMD "$SANDBOX" start
sleep 5

# ─── Verify ─────────────────────────────────────────────────────────
if curl -sf http://localhost:18789/api/health >/dev/null 2>&1; then
  ok "Hermes dashboard is up at http://localhost:18789"
else
  warn "Dashboard may still be starting — check http://localhost:18789 in a moment"
fi

if curl -sf http://localhost:8642/v1/models -H "Authorization: Bearer *** /dev/null 2>&1; then
  ok "Hermes OpenAI API is up at http://localhost:8642"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Tier applied: $TIER"
echo "  Hermes dashboard: http://localhost:18789"
echo "  Hermes OpenAI API: http://localhost:8642"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
