#!/usr/bin/env bash
# provision-pangolin.sh — Install Newt and configure per-device Pangolin tunnel
#
# This runs on the target device during bootstrap or on first setup.
# It installs the Newt client and creates the systemd service that keeps
# the tunnel alive. Supports per-device sub-sub-domain routing.
#
# Environment variables (set by preseed or /etc/serverstick/agent.env):
#   NEWT_ID           — Newt ID (e.g. mriqk2z8tyl84jb)
#   NEWT_SECRET       — Newt secret from Pangolin site creation
#   NEWT_ENDPOINT     — Pangolin Gerbil endpoint (default: gerbil.pangolin.net:50120)
#   DEVICE_NAME       — Device name for subdomain routing (e.g. "nick")

set -euo pipefail

SS_DIR="/etc/serverstick"
SS_BIN="/usr/local/bin"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
log()  { echo -e "${GREEN}[serverstick]${NC} $*"; }
warn() { echo -e "${YELLOW}[serverstick]${NC} ⚠ $*"; }

# ─── Install Newt ───────────────────────────────────────────────────────────

install_newt() {
    if command -v newt &>/dev/null; then
        log "Newt already installed: $(newt --version 2>/dev/null || echo 'unknown')"
        return 0
    fi

    log "Installing Newt (Pangolin tunnel client)..."

    local arch
    arch=$(dpkg --print-architecture 2>/dev/null || echo "amd64")
    case "$arch" in
        amd64) newt_arch="amd64" ;;
        arm64) newt_arch="arm64" ;;
        *) warn "Unsupported arch: $arch"; return 1 ;;
    esac

    # Download latest Newt release
    local newt_url="https://github.com/pangolin-oracle/newt/releases/latest/download/newt-linux-${newt_arch}"
    curl -fsSL "$newt_url" -o "${SS_BIN}/newt"
    chmod +x "${SS_BIN}/newt"

    log "Newt installed: ${SS_BIN}/newt"
}

# ─── Configure Newt ─────────────────────────────────────────────────────────

configure_newt() {
    local newt_id="${NEWT_ID:-${PANGOLIN_NEWT_ID:-}}"
    local secret="${NEWT_SECRET:-${PANGOLIN_SECRET:-}}"
    local endpoint="${NEWT_ENDPOINT:-${PANGOLIN_ENDPOINT:-gerbil.pangolin.net:50120}}"
    local device_name="${DEVICE_NAME:-${SERVERSTICK_DEVICE_NAME:-}}"

    if [[ -z "$newt_id" ]] || [[ -z "$secret" ]]; then
        warn "NEWT_ID or NEWT_SECRET not set. Tunnel will not start."
        warn "Set these in ${SS_DIR}/agent.env or as environment variables."
        return 1
    fi

    log "Configuring Pangolin tunnel for device '${device_name:-unnamed}'..."

    # Write pangolin env file (sourced by systemd service)
    mkdir -p "${SS_DIR}"
    cat > "${SS_DIR}/pangolin.env" <<EOF
# Pangolin tunnel configuration (generated by ServerStick)
# Device: ${device_name:-unknown}
NEWT_ID=${newt_id}
NEWT_SECRET=${secret}
NEWT_ENDPOINT=${endpoint}
EOF
    chmod 600 "${SS_DIR}/pangolin.env"

    log "Pangolin config written to ${SS_DIR}/pangolin.env"
}

# ─── Systemd Service ─────────────────────────────────────────────────────────

install_newt_service() {
    log "Installing Newt systemd service..."

    cat > /etc/systemd/system/serverstick-newt.service <<'EOF'
[Unit]
Description=ServerStick Pangolin Tunnel (Newt)
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/serverstick/pangolin.env
ExecStart=/usr/local/bin/newt --id ${NEWT_ID} --secret ${NEWT_SECRET} --endpoint ${NEWT_ENDPOINT}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable serverstick-newt.service

    log "Newt service installed and enabled."
}

# ─── Start Newt ──────────────────────────────────────────────────────────────

start_newt() {
    log "Starting Newt tunnel..."
    systemctl start serverstick-newt.service || true

    # Wait for connection
    local retries=15
    while [[ $retries -gt 0 ]]; do
        if systemctl is-active --quiet serverstick-newt.service; then
            log "Newt tunnel is active."
            return 0
        fi
        retries=$((retries - 1))
        sleep 2
    done

    warn "Newt tunnel not yet connected after 30s. Check: journalctl -u serverstick-newt"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    install_newt
    configure_newt
    install_newt_service
    start_newt

    local device="${DEVICE_NAME:-${SERVERSTICK_DEVICE_NAME:-<device>}}"
    echo ""
    log "Pangolin tunnel configured for device '${device}'."
    log "Services will be accessible at:"
    log "  https://dash.${device}.serverstick.com   — Dashboard"
    log "  https://home.${device}.serverstick.com   — Homepage"
    log "  https://pdf.${device}.serverstick.com    — Stirling PDF"
    log "  https://bin.${device}.serverstick.com    — PrivateBin"
    log "  https://drop.${device}.serverstick.com   — PairDrop"
    log "  https://kuma.${device}.serverstick.com   — Uptime Kuma"
    log "  https://rembg.${device}.serverstick.com  — Background Removal"
    log "  https://logs.${device}.serverstick.com   — Container Logs"
    echo ""
}

main "$@"