#!/usr/bin/env bash
# provision-pangolin.sh — Install Newt and configure Pangolin tunnel
#
# This runs on the target device during bootstrap.
# It installs the Newt client and creates the systemd service
# that keeps the tunnel alive.
#
# Environment variables (set by preseed or bootstrap):
#   PANGOLIN_NEWT_ID      — Newt ID (e.g. mriqk2z8tyl84jb)
#   PANGOLIN_SECRET       — Newt secret from Pangolin site creation
#   PANGOLIN_ENDPOINT     — Pangolin Gerbil endpoint (e.g. gerbil.pangolin.net:50120)

set -euo pipefail

SS_DIR="/etc/serverstick"
SS_BIN="/usr/local/bin"
SS_LOG="/var/log/serverstick"

GREEN='\033[0;32m'
NC='\033[0m'
log() { echo -e "${GREEN}[serverstick]${NC} $*"; }

# ─── Install Newt ───────────────────────────────────────────────────────────

install_newt() {
    if command -v newt &>/dev/null; then
        log "Newt already installed: $(newt --version 2>/dev/null || echo 'unknown')"
        return 0
    fi

    log "Installing Newt (Pangolin tunnel client)..."

    local arch
    arch=$(dpkg --print-architecture)
    case "$arch" in
        amd64) newt_arch="x86_64" ;;
        arm64) newt_arch="aarch64" ;;
        *) log "Unsupported arch: $arch"; return 1 ;;
    esac

    # Download latest Newt release from Pangolin
    local newt_url="https://github.com/missive/Newt/releases/latest/download/newt-linux-${newt_arch}"
    curl -fsSL "$newt_url" -o "${SS_BIN}/newt"
    chmod +x "${SS_BIN}/newt"

    log "Newt installed: ${SS_BIN}/newt"
}

# ─── Configure Newt ─────────────────────────────────────────────────────────

configure_newt() {
    log "Configuring Pangolin tunnel..."

    local newt_id="${PANGOLIN_NEWT_ID:-}"
    local secret="${PANGOLIN_SECRET:-}"
    local endpoint="${PANGOLIN_ENDPOINT:-gerbil.pangolin.net:50120}"

    if [[ -z "$newt_id" ]] || [[ -z "$secret" ]]; then
        log "WARNING: PANGOLIN_NEWT_ID or PANGOLIN_SECRET not set. Tunnel will not start."
        log "Set these in /etc/serverstick/env or as environment variables."
        return 1
    fi

    # Write Newt config
    mkdir -p "${SS_DIR}"
    cat > "${SS_DIR}/pangolin.env" <<EOF
# Pangolin tunnel configuration (generated by ServerStick bootstrap)
# DO NOT COMMIT THIS FILE
NEWT_ID=${newt_id}
NEWT_SECRET=${secret}
NEWT_ENDPOINT=${endpoint}
EOF
    chmod 600 "${SS_DIR}/pangolin.env"

    log "Pangolin config written to ${SS_DIR}/pangolin.env"
}

# ─── Systemd Service ─────────────────────────────────────────────────────────

install_newt_service() {
    log "Installing Newt systemd service..."

    cat > /etc/systemd/system/serverstick-newt.service <<'EOF'
[Unit]
Description=ServerStick Pangolin Tunnel (Newt)
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/serverstick/pangolin.env
ExecStart=/usr/local/bin/newt --id ${NEWT_ID} --secret ${NEWT_SECRET} --endpoint ${NEWT_ENDPOINT}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable serverstick-newt.service

    log "Newt service installed and enabled."
}

# ─── Start Newt ──────────────────────────────────────────────────────────────

start_newt() {
    log "Starting Newt tunnel..."
    systemctl start serverstick-newt.service || true

    # Wait for connection
    local retries=15
    while [[ $retries -gt 0 ]]; do
        if systemctl is-active --quiet serverstick-newt.service; then
            log "Newt tunnel is active."
            return 0
        fi
        retries=$((retries - 1))
        sleep 2
    done

    log "WARNING: Newt tunnel not yet connected after 30s. Check: journalctl -u serverstick-newt"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    install_newt
    configure_newt
    install_newt_service
    start_newt

    echo ""
    log "Pangolin tunnel configured."
    log "Services will be accessible at:"
    log "  https://home.serverstick.com     — Dashboard"
    log "  https://pdf.serverstick.com      — Stirling PDF"
    log "  https://bin.serverstick.com      — PrivateBin"
    log "  https://drop.serverstick.com     — PairDrop"
    log "  https://kuma.serverstick.com     — Uptime Kuma"
    log "  https://rembg.serverstick.com    — Background Removal"
    log "  https://logs.serverstick.com     — Container Logs"
    log "  https://api.serverstick.com      — Discovery API"
    log "  https://pi.serverstick.com       — Pi Agent"
    echo ""
}

main "$@"